# Generated by Django 3.1 on 2020-01-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('stu_num', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('term', models.CharField(max_length=64)),
                ('activity_name', models.CharField(max_length=64)),
                ('activity_num', models.SmallIntegerField()),
                ('ischeck', models.BooleanField(default=False)),
                ('isagree', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Class_Evaluate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluate_stu_num', models.CharField(max_length=64)),
                ('be_evaluate_stu_num', models.CharField(max_length=64, null=True)),
                ('grade', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comprehensive_Grade',
            fields=[
                ('stu_num', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('stu_major_grade', models.DecimalField(decimal_places=1, max_digits=3)),
                ('activity_grade', models.DecimalField(decimal_places=1, max_digits=3)),
                ('stu_sum_grade', models.DecimalField(decimal_places=1, max_digits=3)),
                ('stu_rank', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Evaluate_Number',
            fields=[
                ('stu_num', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('A_num', models.SmallIntegerField()),
                ('B_num', models.SmallIntegerField()),
                ('C_num', models.SmallIntegerField()),
                ('D_num', models.SmallIntegerField()),
                ('evaluate_grade', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Is_Evaluate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_num', models.CharField(max_length=64)),
                ('be_evaluate_num', models.CharField(max_length=64)),
                ('be_evaluate_name', models.CharField(max_length=64)),
                ('isevaluate', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Major_Grade',
            fields=[
                ('stu_num', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('stu_major_grade', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Scholar_Apply',
            fields=[
                ('stu_num', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('stu_rank', models.SmallIntegerField()),
                ('scholar_name', models.CharField(max_length=64)),
                ('ischeck', models.BooleanField(default=False)),
                ('isagree', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('stu_num', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=64)),
                ('stu_college', models.CharField(max_length=64)),
                ('stu_class', models.CharField(max_length=64)),
            ],
        ),
    ]
